/** ***************************************************************
* Copyright 2020 Advanced Distributed Learning (ADL)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
**************************************************************** */
import React from 'react';
import { Formik, Field } from 'formik';
import * as Yup from 'yup';
import { v4 as uuidv4 } from 'uuid';

import ErrorValidation from '../controls/errorValidation';
import Iri from '../fields/Iri';
import Tags from '../fields/Tags';
import Translations from '../fields/Translations';
import { useSelector } from 'react-redux';

export default function CreateProfileForm({ initialValue, handleSubmit, handleCancel }) {

    const profileRootIRI = useSelector(state => state.application.profileRootIRI);

    let generatedIRIBase = `${profileRootIRI}/${uuidv4()}/`;

    let startingValues;
    if (initialValue) {
        startingValues = { ...initialValue };
        // it's possible that the iri was external and still match, but this is what 
        // the system will use to generate the base of the concept iri, so we'll call it 
        // generated
        let regResults;
        if (initialValue.iri) {
            regResults = new RegExp(`(${profileRootIRI})/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})/(.*)`).exec(initialValue.iri);
            // did our regex hit?
            if (regResults && regResults.length) {
                // matches our rootiri
                startingValues.iriType = regResults[1] ? 'generated-iri' : 'external-iri'
                // captured path stuff after the typical generated base.. like /v/1
                startingValues.iri = regResults[3] || "";
                // make the generated base rootiri/uuid
                generatedIRIBase = `${regResults[1]}/${regResults[2]}/`;
            }
            else {
                startingValues.iriType = 'external-iri'
                startingValues.iri = initialValue.iri;
            }
        }
    }

    return (
        <Formik
            initialValues={startingValues || {
                iriType: "external-iri", iri: '', name: '', description: '', translations: [], moreInformation: '', tags: [],
            }}
            validationSchema={Yup.object({
                hasIRI: Yup.boolean(),
                iri: Yup.string(),
                name: Yup.string()
                    .required('Required'),
                description: Yup.string()
                    .required('Required'),
            })}
            onSubmit={(values) => {
                if (values.iriType === 'generated-iri')
                    values.iri = `${generatedIRIBase}${values.iri}`;
                handleSubmit(values);
            }}
        >
            {(formikProps) => (<>
                <div className="grid-container border-1px border-base-lighter padding-bottom-4 padding-left-4">
                    <div className="grid-row">
                        <h2 className="grid-col-5">Profile Details</h2>
                        <div className="grid-col">
                            <div className="margin-top-3">
                                <span className="text-secondary">*</span> <span className="text-thin text-base font-sans-3xs">indicates required field</span>
                            </div>
                        </div>
                    </div>
                    <form className="usa-form">
                        <Iri message="This profile already has an IRI that is used in xAPI statements"
                            sublabel={<>The IRI is what you will use to identify this concept in xAPI statements. A portion of the IRI depends on the IRI for the profile.
                            You may use an IRI that is managed externally or one that is generated by the profile server.
                                <span className="text-bold"> This is permanent and cannot be changed.</span></>}
                            {...formikProps} generatedIRIBase={generatedIRIBase} profileIRI={true} />

                        <ErrorValidation name="name" type="input">
                            <label className="usa-label" htmlFor="name"><span className="text-secondary">*</span><span className="details-label"> Name</span></label>
                            <Field name="name" type="text" className="usa-input" id="input-name" aria-required="true" />
                        </ErrorValidation>

                        <ErrorValidation name="description" type="input">
                            <label className="usa-label" htmlFor="description"><span className="text-secondary">*</span><span className="details-label"> Description</span></label>
                            <Field name="description" component="textarea" rows="3" className="usa-textarea" id="input-description" aria-required="true" />
                        </ErrorValidation>

                        <label className="usa-label" htmlFor="translations"><span className="details-label">Translations</span></label>
                        <Field name="translations" component={Translations} id="translations" />

                        <label className="usa-label" htmlFor="moreInformation"><span className="details-label">More Information</span></label>
                        <Field name="moreInformation" type="text" className="usa-input" id="input-moreInformation" />

                        <label className="usa-label" htmlFor="tags">
                            <span className="details-label">Tags</span> <br />
                            <span className="usa-hint font-ui-3xs">Put a comma between each one. Example: <strong>tag 1, tag 2, tag 3</strong></span>
                        </label>
                        <Field name="tags" component={Tags} className="usa-input" id="input-tags" />
                    </form>
                </div>
                <button className="usa-button submit-button" type="button" onClick={formikProps.handleSubmit}>
                    {
                        initialValue ? "Save Changes" : "Create Profile"
                    }
                </button>
                <button onClick={handleCancel} className="usa-button usa-button--unstyled" type="reset"><b>Cancel</b></button>

            </>)}
        </Formik>
    )
}
