version: '3'
services:

  server:
    build:
      context: .
    container_name: server
    ports:
      - 127.0.0.1:3005:3005
    depends_on:
      - mongoose
    restart: always
    networks:
      - public    
    environment:
      # - DANGEROUSLY_DISABLE_HOST_CHECK="true"
      - port=3005
      - connectionString
      - profileRootIRI
      - QUERY_RESULT_LIMIT
      - email_user
      - email_pass
      - email_server
      - system_email_from
      - clientURL
      - debug
      - MONGOMS_SYSTEM_BINARY=usr/bin/mongod
      - lockTimeout=600000
      - PUBLIC_URL=/public

  mongoose:
    image: mongo
    container_name: mongoose
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - public

  nginx:
    restart: always
    build:
      context: nginx
      args:
        - HOSTNAME=${HOSTNAME}
    ports:
      - 80:80
      - 443:443
    container_name: docker_nginx
    volumes:
      - ./data/nginx/letsencrypt:/usr/share/nginx/html
      - ./data/certbot/etc:/usr/share/keys
    networks:
      - public

  certbot:
    container_name: 'docker_certbot'
    image: certbot/certbot
    volumes:
      - ./data/keys:/var/lib/letsencrypt
      - ./data/nginx/letsencrypt:/data/letsencrypt
      - ./data/certbot/etc:/etc/letsencrypt
      - ./data/certbot/log:/var/log/letsencrypt
    ports:
      - 8080:8080
    networks:
      - public

networks:
  public:
    driver: bridge      
